language: c

# services: [docker] implies dist: trusty + sudo: required
# c.f. https://github.com/travis-ci/travis-ci/issues/7256
services:
  - docker

cache:
  directories:
    - $HOME/bin

env:
  - VOLUME=host
  - VOLUME=image

before_install:
  - echo $PATH
  - export DOCKER_COMPOSE=${HOME}/bin/docker-compose
  - export DOCKER_COMPOSE_VERSION=1.10.1
  - test -x ${DOCKER_COMPOSE} || (mkdir -p ${HOME}/bin && curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` -o ${DOCKER_COMPOSE} && chmod +x ${DOCKER_COMPOSE})

script:
  - docker-compose --version
  - test "$VOLUME" = "image" && sed -i '/volumes:/d;/data:/d' docker-compose.yml
  - docker-compose up --abort-on-container-exit
