version: '2.1'

services:
  sysbench:
    build: .
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:5.5
    ports:
      - "127.0.0.1::3306"
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: sbtest
    healthcheck:
      test: mysql -Dsbtest -e "SELECT 1"
      interval: "5s"
      retries: 10
